-- Gets you the customer's first name and last name whos points are >= 100
SELECT ACCOUNT.FIRSTNAME, ACCOUNT.LASTNAME 
FROM ACCOUNT 
INNER JOIN CUSTOMER
ON ACCOUNT.ACCOUNTID = CUSTOMER.ACCOUNTID
WHERE CUSTOMER.POINTS >= 100

-- Gets you the number of customers who don't have any points
SELECT COUNT(*)
FROM ACCOUNT 
INNER JOIN CUSTOMER
ON ACCOUNT.ACCOUNTID = CUSTOMER.ACCOUNTID
WHERE CUSTOMER.POINTS = 0