-- Drop dependent tables first (Genre, MovieDirector, MovieCast)
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE MovieCast CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE MovieDirector CASCADE CONSTRAINTS';
  EXECUTE IMMEDIATE 'DROP TABLE Genre CASCADE CONSTRAINTS';
  
  -- Finally, drop the main Movie table
  EXECUTE IMMEDIATE 'DROP TABLE Movie CASCADE CONSTRAINTS';
END;
/

COMMIT;

