-- Find all Discount promotions happening this year
SELECT PROMOTIONID, STOREPROMOTIONS.DESCRIPTION, storepromotions.ENDDATE - storepromotions.STARTDATE as days
FROM STOREPROMOTIONS
WHERE PROMOTIONTYPE = 'Discount'
ORDER BY storepromotions.ENDDATE - storepromotions.STARTDATE;

-- Find Revenue made during promotions
SELECT PROMOTIONID, STOREPROMOTIONS.DESCRIPTION as Promotion, SUM(ORDERS.AMOUNT) as Revenue
FROM STOREPROMOTIONS, ORDERS
WHERE ORDERS.ORDERDATE >= STOREPROMOTIONS.STARTDATE 
AND ORDERS.ORDERDATE < STOREPROMOTIONS.ENDDATE
GROUP BY STOREPROMOTIONS.PROMOTIONID, STOREPROMOTIONS.DESCRIPTION
ORDER BY SUM(ORDERS.AMOUNT) DESC;

-- Find Number of Items Bought during promotions
SELECT 
    sp.PROMOTIONID, 
    sp.DESCRIPTION, 
    SUM(od.QUANTITY) AS Sales
FROM 
    STOREPROMOTIONS sp
    INNER JOIN ORDERS o ON o.ORDERDATE BETWEEN sp.STARTDATE AND sp.ENDDATE
    INNER JOIN ORDERDETAILS od ON od.ORDERID = o.ORDERID
GROUP BY 
    sp.PROMOTIONID, 
    sp.DESCRIPTION
ORDER BY 
    Sales DESC;
