-- Find all Discount promotions happening this year
SELECT PROMOTIONID, STOREPROMOTIONS.DESCRIPTION, storepromotions.ENDDATE - storepromotions.STARTDATE as days
FROM STOREPROMOTIONS
WHERE PROMOTIONTYPE = 'Discount'
ORDER BY storepromotions.ENDDATE - storepromotions.STARTDATE;

-- Find Revenue made during promotions
SELECT PROMOTIONID, STOREPROMOTIONS.DESCRIPTION as Promotion, SUM(ORDERS.AMOUNT) as Revenue
FROM STOREPROMOTIONS, ORDERS
WHERE ORDERS.ORDERDATE >= STOREPROMOTIONS.STARTDATE 
AND ORDERS.ORDERDATE < STOREPROMOTIONS.ENDDATE
GROUP BY STOREPROMOTIONS.PROMOTIONID, STOREPROMOTIONS.DESCRIPTION
ORDER BY SUM(ORDERS.AMOUNT) DESC;

-- Find Number of Items Bought during promotions
SELECT PROMOTIONID, STOREPROMOTIONS.DESCRIPTION, SUM(ORDERDETAILS.QUANTITY) as Sales
FROM STOREPROMOTIONS, ORDERS, ORDERDETAILS
WHERE ORDERS.ORDERID = ORDERDETAILS.ORDERID
AND ORDERS.ORDERDATE BETWEEN STOREPROMOTIONS.STARTDATE AND STOREPROMOTIONS.ENDDATE
GROUP BY STOREPROMOTIONS.PROMOTIONID, STOREPROMOTIONS.DESCRIPTION
ORDER BY SUM(ORDERDETAILS.QUANTITY) DESC;